# Generated by Django 4.0.5 on 2022-06-18 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryoptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryoptions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_name',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='delivery name'),
        ),
    ]
