# Generated by Django 4.0.5 on 2022-06-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_producttype_created_at_producttype_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('-created_at',), 'verbose_name': 'Product Type', 'verbose_name_plural': 'Product Types'},
        ),
    ]
